# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Troels Liebe Bentsen
email: tlb@nversion.dk
description: >
  Blog about things i'm working at the moment
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tlbdk.github.com"
github_username:  tlbdk

# Url settings
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
